//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaperApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeHistory
    {
        public int Id { get; set; }
        public int IdDocument { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public string ChangeDescription { get; set; }
    
        public virtual Document Document { get; set; }
    }
}
